language: php
php:
  - 7.3
before_install:
  - composer clear-cache
install:
  - composer self-update
  - composer install --no-interaction
  - npm install
script:
  - mkdir -p shop-backend
  - mv !(shop-backend) shop-backend
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-frontend.git
  - cd shop-frontend
  - npm run-script build
  - mv build/* $TRAVIS_BUILD_DIR/
  - cd ..
  - sudo rm -R shop-frontend
  - cd shop-backend
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-tests.git
  - cp -R shop-tests/backend ./tests/
  - sudo rm -R shop-tests
  - cd ..
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: shop-354
  on: dev-demo
  skip_cleanup: true
