language: php
php:
- 7.3
before_install:
- composer clear-cache
install:
- composer self-update
- composer install --no-interaction
script:
- git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-tests.git
- cp -R shop-tests/backend $TRAVIS_BUILD_DIR/tests/
- sudo rm -R shop-tests
deploy:
  provider: heroku
  api_key:
    secure: PdvLPOErUBASg/amdAEGnVulPUz7Hf7l10/2cvhbZcZl4HLklfHBqmHKFxPSnMaUCdXYb6P6TVVeV/rnfp8HQMAJP4BasOTNR1Xatajhc5oed2ajuUW7Nw3yb70iZT5SGdCQspiIGkj3DsG3NCPO9fLErb/cttYYDPeDfzzm+bnQ6cd8mw95O2XYOYoFKzhLosZpGSKLbZBesijBHjxEeeFRJ0Y2brOy3xZwXcWD+ir2tXchDQbiuD3Nw2fTro4TgpSqfjx1hVvbqqUtVpSVh2s0tpiBD6TaYwQXaBvv8zvjRVTcsV7Y2rwgcpTu1B5QOroJi9LaF+6VqKcMRk3nwOg3gprCAhUftice9HeJTnJtadVEKpM3JbMBzlZXdbz3pn2OaevcBIEaAzEGQoUGDcP//sSmDSEAAL8cvUGp11bxsmOAOuA8lJM8GtFkrc4axZTQeyeuaqntqEoQvxOXJmkI//4IAeeMzsiDqALjanSeAY7sg0FXs4KsiQKwaJfw6s6wkTtTLCS2uxLJNr2hZz3DOUqQJcQ3sMkq7DdRV1C/XmlWeg9iQoHefL8DPVQlCxRFaDyqHEr0lUgojkh8h94iXA28B1PzCoTCgVyIYa2bdvq9VbTVU/r4soVtx5F2YjljOP3k3v/ENjn9+SEuWvkO22/XjkUOKttos4WhTwU=
  app: shop-354-backend
  on: master
  skip_cleanup: true
